[INFO] [2020-10-29 08:03:58,376] [1028:140623145285440] - db_models.py[line:55]: init sqlite database on standalone mode successfully
