[DEBUG] [2020-10-29 08:05:14,343] [1863:140046620854080] - profile_util.py[line:34]: task_executor.py:187 call table, takes 0.0008993148803710938s
[DEBUG] [2020-10-29 08:05:14,344] [1863:140046620854080] - profile_util.py[line:34]: session.py:178 call collect, takes 0.0008554458618164062s
[DEBUG] [2020-10-29 08:05:14,357] [1863:140046620854080] - profile_util.py[line:34]: task_executor.py:212 call save_as, takes 0.01245880126953125s
[DEBUG] [2020-10-29 08:05:14,493] [1863:140046620854080] - profile_util.py[line:34]: component_properties.py:155 call count, takes 0.0003848075866699219s
[DEBUG] [2020-10-29 08:05:14,494] [1863:140046620854080] - profile_util.py[line:34]: abnormal_detection.py:23 call count, takes 0.0004024505615234375s
[DEBUG] [2020-10-29 08:05:14,526] [1863:140046620854080] - profile_util.py[line:34]: data_io.py:162 call mapValues, takes 0.03212904930114746s
[DEBUG] [2020-10-29 08:05:14,564] [1863:140046620854080] - profile_util.py[line:34]: data_io.py:244 call mapValues, takes 0.03691744804382324s
[DEBUG] [2020-10-29 08:05:14,594] [1863:140046620854080] - profile_util.py[line:34]: tracking_manager.py:201 call save_as, takes 0.02979254722595215s
[DEBUG] [2020-10-29 08:05:14,596] [1863:140046620854080] - profile_util.py[line:34]: session.py:178 call collect, takes 0.0008802413940429688s
[DEBUG] [2020-10-29 08:05:14,615] [1863:140046620854080] - profile_util.py[line:34]: tracking_manager.py:221 call count, takes 0.0006377696990966797s
