[INFO] [2020-10-29 08:26:06,171] [2752:140180035798848] - task_executor.py[line:121]: run 2020102908260459230210 dataio_0 2020102908260459230210_dataio_0 host 10000 task
[INFO] [2020-10-29 08:26:06,172] [2752:140180035798848] - task_executor.py[line:122]: {'DataIOParam': {'input_format': 'dense', 'delimitor': ',', 'data_type': 'float64', 'exclusive_data_type': None, 'tag_with_value': False, 'tag_value_delimitor': ':', 'missing_fill': False, 'default_value': 0, 'missing_fill_method': None, 'missing_impute': None, 'outlier_replace': False, 'outlier_replace_method': None, 'outlier_impute': None, 'outlier_replace_value': 0, 'with_label': True, 'label_name': 'y', 'label_type': 'int', 'output_format': 'dense'}, 'initiator': {'role': 'guest', 'party_id': 10000}, 'job_parameters': {'work_mode': 0, 'model_id': 'arbiter-10000#guest-10000#host-10000#model', 'model_version': '202010290812019279649'}, 'role': {'guest': [10000], 'host': [10000], 'arbiter': [10000]}, 'config': '/fate/examples/federatedml-1.x-examples/homo_logistic_regression/test_homolr_evaluate_job_conf.json', 'dsl': 'examples/federatedml-1.x-examples/homo_logistic_regression/test_homolr_evaluate_job_dsl.json', 'function': 'submit_job', 'local': {'role': 'host', 'party_id': 10000}, 'CodePath': 'federatedml/util/data_io.py/DataIO', 'module': 'DataIO'}
[INFO] [2020-10-29 08:26:06,172] [2752:140180035798848] - task_executor.py[line:123]: {'model': ['pipeline.dataio_0.dataio'], 'data': {'data': ['args.eval_data']}}
[INFO] [2020-10-29 08:26:06,192] [2752:140180035798848] - pipelined_model.py[line:177]: parse DataIOMeta proto object normal
[INFO] [2020-10-29 08:26:06,194] [2752:140180035798848] - pipelined_model.py[line:177]: parse DataIOParam proto object normal
[DEBUG] [2020-10-29 08:26:06,195] [2752:140180035798848] - profile_util.py[line:34]: task_executor.py:187 call table, takes 0.0008280277252197266s
[INFO] [2020-10-29 08:26:06,195] [2752:140180035798848] - task_executor.py[line:202]: start save as task 2020102908260459230210_dataio_0 input data table experiment breast_homo_host
[DEBUG] [2020-10-29 08:26:06,196] [2752:140180035798848] - profile_util.py[line:34]: session.py:178 call collect, takes 0.0007517337799072266s
[DEBUG] [2020-10-29 08:26:06,222] [2752:140180035798848] - profile_util.py[line:34]: task_executor.py:212 call save_as, takes 0.0258328914642334s
[INFO] [2020-10-29 08:26:06,226] [2752:140180035798848] - task_executor.py[line:218]: save as task 2020102908260459230210_dataio_0 input data table to 2020102908260459230210_dataio_0_host_10000 breast_homo_host done
[DEBUG] [2020-10-29 08:26:06,496] [2752:140180035798848] - component_properties.py[line:67]: {'DataIOParam': {'input_format': 'dense', 'delimitor': ',', 'data_type': 'float64', 'exclusive_data_type': None, 'tag_with_value': False, 'tag_value_delimitor': ':', 'missing_fill': False, 'default_value': 0, 'missing_fill_method': None, 'missing_impute': None, 'outlier_replace': False, 'outlier_replace_method': None, 'outlier_impute': None, 'outlier_replace_value': 0, 'with_label': True, 'label_name': 'y', 'label_type': 'int', 'output_format': 'dense'}, 'initiator': {'role': 'guest', 'party_id': 10000}, 'job_parameters': {'work_mode': 0, 'model_id': 'arbiter-10000#guest-10000#host-10000#model', 'model_version': '202010290812019279649'}, 'role': {'guest': [10000], 'host': [10000], 'arbiter': [10000]}, 'config': '/fate/examples/federatedml-1.x-examples/homo_logistic_regression/test_homolr_evaluate_job_conf.json', 'dsl': 'examples/federatedml-1.x-examples/homo_logistic_regression/test_homolr_evaluate_job_dsl.json', 'function': 'submit_job', 'local': {'role': 'host', 'party_id': 10000}, 'CodePath': 'federatedml/util/data_io.py/DataIO', 'module': 'DataIO'}
[DEBUG] [2020-10-29 08:26:06,496] [2752:140180035798848] - component_properties.py[line:74]: need_run: True, need_cv: False
[DEBUG] [2020-10-29 08:26:06,496] [2752:140180035798848] - component_properties.py[line:118]: has_train_data: False, has_eval_data: False, has_normal_data: True
[DEBUG] [2020-10-29 08:26:06,498] [2752:140180035798848] - profile_util.py[line:34]: component_properties.py:155 call count, takes 0.0018448829650878906s
[DEBUG] [2020-10-29 08:26:06,499] [2752:140180035798848] - model_base.py[line:210]: In extract_data, data input: {'args.data': <arch.api.impl.based_1x.table.DTable object at 0x7f791b142a20>}
[DEBUG] [2020-10-29 08:26:06,499] [2752:140180035798848] - model_base.py[line:87]: func: <bound method DataIO.transform of <federatedml.util.data_io.DataIO object at 0x7f791b142668>>
[INFO] [2020-10-29 08:26:06,499] [2752:140180035798848] - data_io.py[line:141]: start to read dense data and change data to instance
[DEBUG] [2020-10-29 08:26:06,500] [2752:140180035798848] - profile_util.py[line:34]: abnormal_detection.py:23 call count, takes 0.0010330677032470703s
[DEBUG] [2020-10-29 08:26:06,501] [2752:140180035798848] - data_io.py[line:95]: header is y,x0,x1,x2,x3,x4,x5,x6,x7,x8,x9,x10,x11,x12,x13,x14,x15,x16,x17,x18,x19,x20,x21,x22,x23,x24,x25,x26,x27,x28,x29
[DEBUG] [2020-10-29 08:26:06,501] [2752:140180035798848] - data_io.py[line:96]: sid_name is id
[DEBUG] [2020-10-29 08:26:06,544] [2752:140180035798848] - profile_util.py[line:34]: data_io.py:155 call mapValues, takes 0.04254484176635742s
[DEBUG] [2020-10-29 08:26:06,562] [2752:140180035798848] - profile_util.py[line:34]: data_io.py:158 call mapValues, takes 0.016702651977539062s
[DEBUG] [2020-10-29 08:26:06,566] [2752:140180035798848] - profile_util.py[line:34]: io_check.py:29 call count, takes 0.004288673400878906s
[DEBUG] [2020-10-29 08:26:06,590] [2752:140180035798848] - profile_util.py[line:34]: data_io.py:241 call join, takes 0.023303985595703125s
[DEBUG] [2020-10-29 08:26:06,594] [2752:140180035798848] - profile_util.py[line:34]: io_check.py:35 call count, takes 0.004114389419555664s
[DEBUG] [2020-10-29 08:26:06,594] [2752:140180035798848] - io_check.py[line:36]: num row of input: 228 -> num row of output: 228
[DEBUG] [2020-10-29 08:26:06,595] [2752:140180035798848] - model_base.py[line:99]: saved_result is : [<arch.api.impl.based_1x.table.DTable object at 0x7f1513739908>], data_output: <arch.api.impl.based_1x.table.DTable object at 0x7f1513739908>
[DEBUG] [2020-10-29 08:26:06,637] [2752:140180035798848] - profile_util.py[line:34]: tracking_manager.py:201 call save_as, takes 0.041982412338256836s
[DEBUG] [2020-10-29 08:26:06,640] [2752:140180035798848] - profile_util.py[line:34]: session.py:178 call collect, takes 0.0011410713195800781s
[DEBUG] [2020-10-29 08:26:06,723] [2752:140180035798848] - profile_util.py[line:34]: tracking_manager.py:221 call count, takes 0.018543720245361328s
[INFO] [2020-10-29 08:26:06,731] [2752:140180035798848] - pipelined_model.py[line:72]: Save dataio_0 default DataIOMeta buffer
[INFO] [2020-10-29 08:26:06,731] [2752:140180035798848] - pipelined_model.py[line:72]: Save dataio_0 default DataIOParam buffer
[INFO] [2020-10-29 08:26:06,743] [2752:140180035798848] - pipelined_model.py[line:77]: Save dataio_0 default successfully
[INFO] [2020-10-29 08:26:06,768] [2752:140180035798848] - task_executor.py[line:160]: task 2020102908260459230210_dataio_0 host 10000 start time: 2020-10-29 08:26:05
[INFO] [2020-10-29 08:26:06,769] [2752:140180035798848] - task_executor.py[line:161]: task 2020102908260459230210_dataio_0 host 10000 end time: 2020-10-29 08:26:06
[INFO] [2020-10-29 08:26:06,769] [2752:140180035798848] - task_executor.py[line:162]: task 2020102908260459230210_dataio_0 host 10000 takes 0.844s
[INFO] [2020-10-29 08:26:06,769] [2752:140180035798848] - task_executor.py[line:164]: finish 2020102908260459230210 dataio_0 2020102908260459230210_dataio_0 host 10000 success task
