[INFO] [2020-10-29 08:26:08,747] [2813:140653361506112] - task_executor.py[line:121]: run 2020102908260459230210 homo_lr_0 2020102908260459230210_homo_lr_0 host 10000 task
[INFO] [2020-10-29 08:26:08,747] [2813:140653361506112] - task_executor.py[line:122]: {'HomoLogisticParam': {'penalty': 'L2', 'tol': 1e-05, 'alpha': 0.01, 'optimizer': 'sgd', 'batch_size': 320, 'learning_rate': 0.15, 'init_param': {'init_method': 'zeros', 'init_const': 1, 'fit_intercept': True, 'random_seed': None}, 'max_iter': 3, 'early_stop': 'diff', 'encrypt_param': {'method': 'Paillier', 'key_length': 1024}, 'predict_param': {'threshold': 0.5}, 'cv_param': {'n_splits': 4, 'mode': 'hetero', 'role': 'guest', 'shuffle': True, 'random_seed': 33, 'need_cv': False}, 'decay': 1, 'decay_sqrt': True, 'multi_class': 'ovr', 'validation_freqs': None, 'stepwise_param': {'score_name': 'AIC', 'mode': 'hetero', 'role': 'guest', 'direction': 'both', 'max_step': 10, 'nvmin': 2, 'nvmax': None, 'need_stepwise': False}, 'early_stopping_rounds': None, 'metrics': ['auc', 'ks'], 'use_first_metric_only': False, 're_encrypt_batches': 2, 'aggregate_iters': 1}, 'initiator': {'role': 'guest', 'party_id': 10000}, 'job_parameters': {'work_mode': 0, 'model_id': 'arbiter-10000#guest-10000#host-10000#model', 'model_version': '202010290812019279649'}, 'role': {'guest': [10000], 'host': [10000], 'arbiter': [10000]}, 'config': '/fate/examples/federatedml-1.x-examples/homo_logistic_regression/test_homolr_evaluate_job_conf.json', 'dsl': 'examples/federatedml-1.x-examples/homo_logistic_regression/test_homolr_evaluate_job_dsl.json', 'function': 'submit_job', 'local': {'role': 'host', 'party_id': 10000}, 'CodePath': 'federatedml/linear_model/logistic_regression/homo_logsitic_regression/homo_lr_host.py/HomoLRHost', 'module': 'HomoLR'}
[INFO] [2020-10-29 08:26:08,747] [2813:140653361506112] - task_executor.py[line:123]: {'model': ['pipeline.homo_lr_0.homolr'], 'data': {'eval_data': ['dataio_0.train']}}
[INFO] [2020-10-29 08:26:08,770] [2813:140653361506112] - task_executor.py[line:202]: start save as task 2020102908260459230210_homo_lr_0 input data table output_data_2020102908260459230210_dataio_0 63eae794-19c0-11eb-a9a9-0242ac120002
[INFO] [2020-10-29 08:26:08,833] [2813:140653361506112] - task_executor.py[line:218]: save as task 2020102908260459230210_homo_lr_0 input data table to 2020102908260459230210_homo_lr_0_host_10000 63eae794-19c0-11eb-a9a9-0242ac120002 done
[INFO] [2020-10-29 08:26:24,574] [2813:140653361506112] - one_vs_rest.py[line:287]: Create one_vs_rest object, role: host, mode: homo
[INFO] [2020-10-29 08:26:24,577] [2813:140653361506112] - random_padding_cipher.py[line:56]: synchronizing uuid
[INFO] [2020-10-29 08:26:24,578] [2813:140653361506112] - random_padding_cipher.py[line:58]: local uuid=c4ca4238a0b923820dcc509a6f75849b
[INFO] [2020-10-29 08:26:24,579] [2813:140653361506112] - random_padding_cipher.py[line:60]: Diffie-Hellman keys exchanging
[INFO] [2020-10-29 08:26:24,688] [2813:140653361506112] - random_padding_cipher.py[line:62]: Diffie-Hellman exchanged keys {'cfcd208495d565ef66e7dff9f98764da': mpz(77655039093400513164206379020365150409144985741022247774818088233416075657482966533625322605735982914895657756650501310083531006234431481255218374803697812790331400085259528658444392799418290193686726362864993505607310302082396229867754681574824986485714448151720263944760875992884343777900305269055474654494)}
[ERROR] [2020-10-29 08:26:24,693] [2813:140653361506112] - task_executor.py[line:144]: 'NoneType' object has no attribute 'fit_intercept'
Traceback (most recent call last):
  File "/fate/fate_flow/driver/task_executor.py", line 135, in run_task
    run_object.run(component_parameters, task_run_args)
  File "/fate/federatedml/model_base.py", line 91, in run
    this_data_output = func(*params)
  File "/fate/federatedml/linear_model/logistic_regression/base_logistic_regression.py", line 103, in load_model
    self.init_param_obj.fit_intercept = meta_obj.fit_intercept
AttributeError: 'NoneType' object has no attribute 'fit_intercept'
[INFO] [2020-10-29 08:26:24,707] [2813:140653361506112] - task_executor.py[line:160]: task 2020102908260459230210_homo_lr_0 host 10000 start time: 2020-10-29 08:26:08
[INFO] [2020-10-29 08:26:24,708] [2813:140653361506112] - task_executor.py[line:161]: task 2020102908260459230210_homo_lr_0 host 10000 end time: 2020-10-29 08:26:24
[INFO] [2020-10-29 08:26:24,708] [2813:140653361506112] - task_executor.py[line:162]: task 2020102908260459230210_homo_lr_0 host 10000 takes 16.18s
[INFO] [2020-10-29 08:26:24,708] [2813:140653361506112] - task_executor.py[line:164]: finish 2020102908260459230210 homo_lr_0 2020102908260459230210_homo_lr_0 host 10000 failed task
